src/distributions/gamma.jl
src/distributions/gamma_shape_rate.jl
src/nodes/gamma.jl
src/nodes/gamma_shape_rate.jl

The last fix for the `loggammamean` function was not entirely correct. The `loggammamean` function is now correct under the Stirling approximation. Furthermore this PR simplifies the average energies as there were no terms in the current version that cancelled out.

Fix loggammamean

---

src/rule.jl
src/rules/addition/in1.jl
src/rules/addition/in2.jl
src/rules/addition/out.jl
src/rules/mv_normal_mean_covariance/mean.jl
src/rules/mv_normal_mean_covariance/out.jl
src/rules/mv_normal_mean_precision/mean.jl
src/rules/mv_normal_mean_precision/out.jl
src/rules/mv_normal_mean_precision/precision.jl
test/rules/mv_normal_mean_covariance/test_mean.jl
test/rules/mv_normal_mean_covariance/test_out.jl
test/rules/mv_normal_mean_precision/test_mean.jl
test/rules/mv_normal_mean_precision/test_out.jl
test/rules/mv_normal_mean_precision/test_precision.jl
test/runtests.jl

This PR adds update rules for the multivariate normal node. It optimizes some rules to potentially reduce the number of matrix inversions. Furthermore it includes tests for the added rules.

extend update rules for mvnormal

---

src/ReactiveMP.jl
src/distributions.jl
src/rules/addition/in1.jl
src/rules/addition/in2.jl
src/rules/addition/marginals.jl
src/rules/addition/out.jl

This PR includes new rules for computing the marginal and messages when all "interfaces" are of `UnivariateNormalDistributionsFamily` type.

Extend Addition node rules

---

Project.toml
src/marginal.jl
src/node.jl
src/nodes/gamma_mixture.jl
src/variables/random.jl
test/runtests.jl

[Aqua.jl](https://github.com/JuliaTesting/Aqua.jl) is a package that makes it easy to do some consistency checks.
This PR adds Aqua as a test dependency, and makes some small changes to make Aqua happy.
Note that ambiguity tests are disabled. Currently there are 148 ambiguities, for example
```julia
Ambiguity #148
make_node(fform::Function, autovar::ReactiveMP.AutoVar, args::ReactiveMP.ConstVariable...; kwargs...) in ReactiveMP at /home/chad/git/ReactiveMP.jl/src/node.jl:683
make_node(fform::typeof(+), autovar::ReactiveMP.AutoVar, args::ReactiveMP.AbstractVariable...; kwargs...) in ReactiveMP at /home/chad/git/ReactiveMP.jl/src/node.jl:845
```

add Aqua tests, get them to pass

---

src/nodes/normal_mixture.jl

This PR fixes average energy score function signature for Gaussian Mixture node so it can work with different gaussian parametrisation.

fix(): Fix for GaussianMixture Node average energy function

---

src/constraints/form/form_fixed_marginal.jl

Here is a small PR that enables immobilizing the marginal distribution such that it remains fixed during inference.

Marginal constraint

---

src/nodes/transition.jl
src/rules/transition/in.jl
src/rules/transition/marginals.jl
src/rules/transition/out.jl

These rules implement analytical solutions for the Transition node when transition matrix is fixed and known (PointMass).

feat: add more rules for Transition node

---

src/nodes/dot_product.jl

This PR makes `dot` function visible without need to `using LinearAlgebra`

fix: reexport dot product from LinearAlgebra

---

src/distributions/pointmass.jl
test/distributions/test_pointmass.jl

This PR implements `mode` for `PointMass`.

fix: add mode method for point mass

---

src/constraints/form/form_point_mass.jl
src/distributions/function.jl
test/constraints/form/test_form_point_mass.jl

This PR fixes small issue with point mass form constraint and (possibly) undefined `variate_form` or `value_support` called on objects (for types it should be always defined).

fix: minor fix for pointmass form constraint

---

src/distributions/gamma.jl
src/distributions/gamma_shape_rate.jl

The mode of a GammaShapeRate distribution is now calculated by extracting the shape and rate parameters, inverting the rate to a scale parameter, defining a GammaShapeScale distribution and calling Distributions.jl's mode calculation.
Notes:
-  GammaShapeScale inherits mode calculation because it is a redefinition of Distributions.Gamma.
- In case of shape < 1, mode calculation throws identical error to Distributions.Gamma mode calculation.

Add mode calculation for GammaShapeRate distribution

---

docs/make.jl
docs/src/lib/methods.md
docs/src/man/getting-started.md

This PR adds the list of exported methods to the documentation. Fixes #114

docs: add list of exported methods #114

---

src/distributions/categorical.jl
src/distributions/contingency.jl
src/rules/transition/marginals.jl
test/distributions/test_contingency.jl

This PR adds documentation for the `Contingency` distribution (cp from ForneyLab) and adds an optional `renormalize` argument. By default `Contingency` renormalizes its input, but it is possible to normalize input matrix by hand and pass `Val(false)` to disable automatic renormalization (this potentially saves some allocations :grin:)

fix: automatically renormalize Contingency matrix

---

src/constraints/spec/factorisation_spec.jl
test/constraints/spec/test_factorisation_spec.jl

This PR fixes and adds extra tests for preoptimised dispatch rules for unspecified constraints and a stochastic node with 2 inputs.
Details for triggering the bug:
- Node must be stochastic
- Node must have 1 input and 1 output
- Both interfaces must connect to random variables
- There must be no constraints specified (even empty)

fix preoptimised factorisation constraint rules for nodes with 2 inputs

---

src/node.jl

This PR adds new diagnostical error message in case if user made a mistake in a model specification and passed an incompatible number of arguments to some node.
```julia
struct Accept2Arguments end
@node Accept2Arguments Stochastic [ out, in1, in2 ]
@model function mymodel()
a ~ NormalMeanVariance(0.0, 1.0)
b ~ NormalMeanVariance(0.0, 1.0)
c ~ NormalMeanVariance(0.0, 1.0)
d = datavar(Float64)
d ~ Accept2Arguments(a, b, c) # <- Before this PR the error message was uninformative
end

Add error for incompatible number of arguments in the model spec

---

src/constraints/spec/factorisation_spec.jl
src/variable.jl
test/constraints/spec/test_factorisation_spec.jl

This PR fixes a case when factorisation constraints resolution engine failed in case if model had anonymous random variables created from deterministic node. This PR also must improve performance a bit as previously factorisation constraints ran for deterministic nodes but the result was ignored. I didn't benchmark it though. In the fixed version we short-circuit on deterministic nodes and skip the computation of local factorisations.

Fix factorisation constraints for anonymous random variables from deterministic functions 

---

src/inference.jl

This PR changes the behaviour of the `inference` function such that it shows the original stack-trace in case if `StackOverflowError` occured. Previously if stack-overflow error occurred somewhere in the user code the original stack-trace was overwritten, which made debugging harder.

Show the original stack trace for `StackOverflowError` in the `inference` function

---

src/distributions/pointmass.jl
test/distributions/test_pointmass.jl

This PR adds `Base.size` method for the `PointMass` distribution

add Base.size method for pointmass

---

src/distributions/pointmass.jl
src/distributions/wishart.jl
src/distributions/wishart_inverse.jl
src/nodes/mv_normal_mean_covariance.jl
src/nodes/wishart.jl
src/nodes/wishart_inverse.jl
test/distributions/test_pointmass.jl
test/distributions/test_wishart.jl
test/distributions/test_wishart_inverse.jl

This PR fixes #191 and adds `mean(::typeof(cholinv), distribution)` for cases where we know that matrix (or matrix-variate distribution) must be squared positive-definite. `mean(::typeof(inv), ::PointMass)` now uses `inv` by default.

Add `mean(::cholinv)`

---

src/distributions/wishart.jl
src/rules/mv_normal_mean_precision/precision.jl
src/rules/normal_mixture/p.jl
src/rules/wishart/marginals.jl
src/rules/wishart/out.jl
test/distributions/test_sample_list.jl
test/distributions/test_wishart.jl
test/models/test_mv_iid.jl
test/rules/mv_normal_mean_precision/test_precision.jl
test/rules/wishart/test_marginals.jl
test/rules/wishart/test_out.jl

This PR fixes #193 by changing `WishartMessage` to store an inverse of its scale-matrix. This avoids unnecessary matrix invertions and correctly handles inference of precision matrix when mean is known. This fix potentially makes inference a bit faster too (way less inversions), but I haven't done any benchmarks. From the user perspective nothing changed really. The only one downside of this PR is that it is no longer possible to create an improper `Wishart` prior (because ReactiveMP.jl internally converts `Wishart` prior to `WishartMessage` which does one invertion).

Fix mv-precision inference with known mean

---

src/model.jl
test/test_model.jl

This PR fixes a bug when inference engine incorrectly attempted to create a node with an `AutoVar` object. Usually `AutoVar` object must be converted to either a new `RandomVariable` or reference an already existing variable. That didn't happen for the `tuple`-based variables, because of the incorrect type dispatch specification in the `make_node` function.

Fix interaction between `autovar` and variables in a form of a tuple 

---

src/rule.jl

Support indexed rules in `@call_rule` macro 

---

Project.toml
src/ReactiveMP.jl
src/approximations/cvi.jl
src/distributions/function.jl
src/distributions/normal.jl
src/nodes/delta/delta.jl
src/rules/delta/cvi/in.jl
src/rules/delta/cvi/marginals.jl
src/rules/delta/cvi/out.jl
test/approximations/test_cvi.jl
test/approximations/test_fisher_matrix.jl
test/distributions/test_normal.jl
test/nodes/delta/cvi/test_cvi.jl
test/rules/delta/cvi/test_in.jl
test/rules/delta/cvi/test_marginals.jl
test/rules/delta/cvi/test_out.jl
test/runtests.jl

This PR makes the CVI Approximation more stable and a bit more:
1. New optional parameter `proper_message`: ensuring that after the division, the message will be a proper distribution
2. adds more tests for the CVI rules
3. adds  a CVI parameter `grad`: the user can use it to change the differentiation procedure (e.g., compute hessian with Zygote)
4. fixes the lognormalizer/hessian sing issue
5. adds clarification comments
6. rename `render_cvi` -> `prod(approximation::ProdCVI, ...)`
7. the `ForwardDiff`hessian/grade computation use 10% less memory.
8. added a new hyperparameter for the CVI `n_gradpoints`: optional, defaults to 1, the number of points to estimate the likelihood gradient (dist*logp). It radically improves CVI precision (a gamma test to prove it added).

CVI stability fix

---

src/distributions/bernoulli.jl
test/approximations/test_cvi.jl
test/distributions/test_bernoulli.jl

The purpose of this pull request is to make the functionality of the CVI to work with the Bernoulli distribution. The following changes have been made:
1. The sign of the Bernoulli log-normalizer has been corrected.
2. A new test has been added to ensure that the Bernoulli natural parameters align with `ProdAnalytical()`.
3. A test has been added to verify that `prod(::CVI, ::Bernoulli, ::Bernoulli)` operates as intended.
With these changes in place, the CVI with Bernoulli distribution works.

Fix prod CVI Bernouilli

---

Makefile
docs/src/extra/contributing.md

convert testset to test_args

---

src/distributions/mv_normal_mean_covariance.jl
src/distributions/mv_normal_mean_precision.jl
src/distributions/mv_normal_weighted_mean_precision.jl
src/distributions/normal_mean_precision.jl
src/distributions/normal_mean_variance.jl
src/distributions/normal_weighted_mean_precision.jl
src/distributions/pointmass.jl
src/variables/constant.jl
test/distributions/test_mv_normal_mean_covariance.jl
test/distributions/test_mv_normal_mean_precision.jl
test/distributions/test_mv_normal_weighted_mean_precision.jl
test/distributions/test_normal_mean_precision.jl
test/distributions/test_normal_mean_variance.jl
test/distributions/test_normal_weighted_mean_precision.jl
test/distributions/test_pointmass.jl
test/rules/bernoulli/test_p.jl
test/variables/test_constant.jl

This PR implements the following and closes #266 :
- Allows for using `UniformScaling` objects in `GraphPPL`.
- Implements multivariate normal constructors that convert `UniformScaling` objects into `Diagonal` matrices according to the length of the (weighted) mean vector.
- Further constrains the specialized `prod` function for multivariate normal distributions to exclude `Diagonal` matrices.

Fix uniformscaling

---

src/node.jl
src/nodes/delta/delta.jl
src/rule.jl

chore(): improve allocation profile for rule dispatching

---

src/distributions/bernoulli.jl
src/rules/transition/in.jl
src/rules/transition/out.jl
test/distributions/test_bernoulli.jl
test/rules/transition/test_a.jl
test/rules/transition/test_in.jl
test/rules/transition/test_out.jl
test/runtests.jl

Please take a look at the rule redefinition for the out interface of the Transition node,  as I made it dispatch on ContinuousMatrixDistribution rather than MatrixDirichlet. This might break if the user supplies a transition matrix with negative values, as it will throw a DomainError on the log function.

283 the mean field rules for the transition node are not generic

---

src/rules/normal_mean_precision/mean.jl
src/rules/normal_mean_precision/out.jl
src/rules/normal_mean_variance/mean.jl
src/rules/normal_mean_variance/out.jl
test/rules/normal_mean_precision/test_mean.jl
test/rules/normal_mean_precision/test_out.jl
test/rules/normal_mean_variance/test_mean.jl
test/rules/normal_mean_variance/test_out.jl

This PR adds missing rules for univariate normal nodes. The rules are a mere copy of the multivariate node.

Add rules for univariate normal

---

src/marginal.jl
src/message.jl
src/node.jl
src/nodes/delta/delta.jl
src/rule.jl
test/runtests.jl

This PR removes the code that overrides the default behaviour of the `Base.nameof` as suggested in https://github.com/JuliaTesting/Aqua.jl/issues/95#issuecomment-1486526905 .
This makes it possible to test if `ReactiveMP` pirate some methods from other packages, which it actually does for methods like
```julia
mean(::typeof(log), distribution::Gamma) = ...
```
We need this methods and its technically the piracy, but should be safe. So I still keep `piracy = false` check from the `Aqua`.

do not override Base.nameof

---

src/rules/multiplication/A.jl
src/rules/multiplication/in.jl
src/rules/multiplication/out.jl
test/rules/multiplication/test_A.jl
test/rules/multiplication/test_in.jl
test/rules/multiplication/test_out.jl
test/runtests.jl

This PR adds rules for the multiplication node. These additional rules cover the product of two random variables drawn from univariate distributions.
This PR relates to the issue #265 .

Add multiplication rules for two univariate random variables

---

src/rules/bernoulli/out.jl

This PR does 2 things:
1. It generalizes the dispatching of the Bernoulli rules 
2. I believe it also increases robustness of the actual computations
With respect to 1, I am not sure whether this generalization is formally allowed, because there is no check for the domain of the variable over which we integrate. However, we currently also do not constrain the `PointMass` distribution.

generalize bernoulli update rule and improve robustness

---

src/helpers/algebra/cholesky.jl
test/algebra/test_cholesky.jl

This PR adds `cholinv` and `cholsqrt` methods for `UniformScaling`. I noticed during some experiments, where some rules failed to take `cholinv`.

add cholinv-family methods for UniformScaling

---

src/constraints/prod/prod_generic.jl
src/distributions/function.jl
src/distributions/sample_list.jl
test/distributions/test_function.jl
test/runtests.jl

This PR fixes #323 and adds non-included tests for the `function.jl` (which were failing btw, oops).

Make the sample list approximation more generic

---

src/ReactiveMP.jl
src/addons/debug.jl
src/variables/variable.jl
test/addons/test_debug.jl
test/runtests.jl

This PR adds a new addon, which evaluates a function over the output of a rule or product. It can be used to effectively track down the first occurences of NaN's or Inf's.
For example, the code below will throw an error, when the parameters of the output distribution become NaN for some reason, and will describe the location where this occurs.
```julia
checkfornans(x) = isnan(x)
checkfornans(x::AbstractArray) = any(checkfornans.(x))
checkfornans(x::Tuple) = any(checkfornans.(x))
inference(
...
addons = (AddonDebug(dist -> checkfornans(params(dist))),)
)
```
This PR might also be relevant for #162. @Sepideh-Adamiat @wmkouw .
This PR closes https://github.com/biaslab/RxInfer.jl/issues/116

Add debug addons

---

src/rules/transition/out.jl
test/rules/multiplication/test_A.jl
test/rules/multiplication/test_out.jl

This PR adds a temporary fix for the transition node, as sf's don't play nicely with @call_rule

Temporary fix for incompatibility @call_rule with addons

---

src/distributions/normal.jl
test/approximations/test_cvi.jl

This update includes the use of `n_gradpoints` in the CVI structure for the function `prod(approximation::CVI, left, dist::GaussianDistributionsFamily)`, aligning it with its implementation for other distributions. The adjustment has led to improved performance and more robust test results, allowing for higher tolerance levels.

Improving the `prod` function for Gaussian Distributions in CVI Approximation

---

src/distributions/gamma_shape_rate.jl
test/distributions/test_gamma.jl

fix sampling from GammaShapeRate

---

src/helpers/algebra/common.jl
src/helpers/algebra/standard_basis_vector.jl
test/algebra/test_common.jl
test/algebra/test_standard_basis_vector.jl

Fix v_a_vT and StandardBasisVector

---

src/rule.jl
test/test_rule.jl

Allow returning addons from the `@call_rule`

---

src/variables/variable.jl
test/variables/test_variable.jl

For the RxInfer [issue](https://github.com/biaslab/RxInfer.jl/issues/101).

Upate for PointMass initmarginals and initmasseges

---

src/variables/variable.jl
test/variables/test_variable.jl

This PR aims to resolve https://github.com/biaslab/RxInfer.jl/issues/175.

feat: add @assert length check into setmarginals! and setmessages!

---

src/nodes/mv_normal_weighted_mean_precision.jl
src/rules/mv_normal_weightedmean_precision/out.jl
src/rules/prototypes.jl
test/nodes/test_mv_normal_weightedmean_precision.jl
test/rules/mv_normal_weightedmean_precision/test_out.jl
test/runtests.jl

This PR encompasses the following contributions for the `MvNormalWeightedMeanPrecision` node:
1. Fix for average energy.
2. Addition of rules for the out interface (particularly useful for priors).
3. Inclusion of missing tests.

Add rules and tests for MvNormalWeightedMeanPrecision node

---

src/nodes/uninformative.jl
src/rules/uninformative/out.jl
test/nodes/test_uninformative.jl
test/runtests.jl

Another attempt to #373 . Spotted by @wouterwln & @bartvanerp . New logic for the predictions did not take into account that someone would want to define a rule that accepts `Missing` as an argument, which is sent out of `Uninformative` node.  This PR changes the outbound message rule for the `Uninformative` node and allows users to define their rules with `Uninformative` arguments.

Change rules for the uninformative node

---

src/nodes/delta/delta.jl
src/nodes/delta/layouts/cvi.jl
src/nodes/delta/layouts/default.jl

This PR allows to use the `where { pipeline = ... }` syntax with the deterministic nodes.

Allow extra pipeline stages in the delta node

---

src/constraints/specifications/constraints.jl
src/constraints/specifications/factorisation.jl
src/constraints/specifications/form.jl
src/node.jl
src/nodes/mixture.jl
test/node_tests.jl

src/node.jl : FullFactorisation replaced by BetheFactorisation and FullFactorisation become depricated and an alias for BetheFactorisation.
test/node_tests.jl : duplicate basic test of FullFactorisation with BetheFactorisation.

Full factorisation new name

---

src/nodes/nodes.jl
test/nodes/nodes_tests.jl

Fixes a bug found by @albertpod . (The formatter fails, but its an issue with the entire version. Lets skip it for now, locally tests pass.)

add sdtype method for distribution objects

---

src/message.jl
src/variables/data.jl
test/nodes/predefined/delta/delta_tests.jl
test/testutilities.jl
test/variables/data_tests.jl

In our model setup, we handle a special case where certain nodes depend on fixed inputs. Instead of making a new node, we connect them directly to the input. This saves us from writing rules for passing messages and just uses the fixed input values. But, there was a bug. It only worked for marginal calculations, not for messages. This update fixes that, making sure all calculations use the linked inputs, and adds a few tests to make sure it works.
Initially found by @ismailsenoz

Fix for linked datavars

---

src/nodes/predefined/continuous_transition.jl
src/rules/continuous_transition/W.jl
src/rules/continuous_transition/a.jl
src/rules/continuous_transition/x.jl
src/rules/continuous_transition/y.jl
test/nodes/predefined/continuous_transition_tests.jl
test/rules/continuous_transition/W_tests.jl
test/rules/continuous_transition/a_tests.jl
test/rules/continuous_transition/x_tests.jl
test/rules/continuous_transition/y_tests.jl

This PR addresses issue #401  by introducing a new set of rules for the `CTransition`node. Mainly, the new rules enable mean-field constraint around the node.

Add MF rules for CTransition

---

src/nodes/predefined/poisson.jl

Average energy computation for Poisson node assumed samples are only positive. However, Poisson samples are non-negative. This PR fixes that by starting the average energy computation from 0.

Fix poisson average energy computation

---

src/nodes/dependencies.jl

After a discussion with @ThijsvdLaar , we discovered that those 2 functions are only ever used inside themselves, and are not used in any `RxInfer` or `ReactiveMP` tests. I'm not sure if these functions are necessary or if they can be deleted, but it seems that `functional_dependencies` does what these functions were supposed to do.

remove msg_dep and mar_dep functions

---

ext/ReactiveMPProjectionExt/ReactiveMPProjectionExt.jl
ext/ReactiveMPProjectionExt/rules/marginals.jl
test/ext/ReactiveMPProjectionExt/rules/marginals_tests.jl

This PR:
1.  Augments the `ProjectedTo` structure with conditioners to in marginal rule computations for delta node. Tests with Binomial and Categorical inputs-outputs.
2. Defines the following products:
`BayesBase.prod(::GenericProd, something::DivisionOf, division::DivisionOf) ` and `BayesBase.prod(::GenericProd, productof::ProductOf, divisionof::DivisionOf) `.
3. Makes`DivisionOf` structure callable.

Add conditioners to ProjectedTo to allow for conditioned distributions in marginal computations

---

ext/ReactiveMPProjectionExt/rules/out.jl

This PR changes the out message rule for delta node such that the rule uses `project_to` from `ExponentialFamilyProjection` and simplifies the code.

Adapt out message rule for delta node to new syntax of ExponentialFamilyProjection

---

src/constraints/form.jl
test/constraints/form_tests.jl

This is a part of https://github.com/ReactiveBayes/RxInfer.jl/issues/335
The associated RxInfer PR is https://github.com/ReactiveBayes/RxInfer.jl/pull/347

Move the check for `ProductOf` to `RxInfer`

---

docs/src/lib/message.md
src/message.jl
src/nodes/dependencies.jl
src/nodes/predefined/delta/layouts/cvi.jl
src/nodes/predefined/delta/layouts/default.jl
test/message_tests.jl

Fix typo in DeferredMessage

---

src/rules/transition/in.jl
src/rules/transition/out.jl
test/rules/transition/out_tests.jl

With `UnfactorizedData`, we should be able to send `PointMass` messages with a factorized `a` as well. The rules are the same as for a Categorical (as far as I can see) but we didn't dispatch on them yet.

Relax rules for structured VMP in Transition node

---

.github/workflows/ci.yml
Project.toml
test/ext/ReactiveMPProjectionExt/rules/out_tests.jl
test/nodes/nodes_tests.jl
test/rules/continuous_transition/x_tests.jl

This pull request fixes some tests for the new version of Julia. Continuous transition rules were using ill-defined covariance matrices, perhaps inverse didn't work well on those and my guess is that it worked before by chance. I made them more stable by adding a diagonal term. The output of `out` rules for CVI projection changed slightly, but its a stochastic method, so for now I simply adjusted parameters of one of the tests. At last, we used internal functionality from `Docs` which has changed, I replaced it with public API to retrieve docs.

Fix tests for Julia v1.11

---

src/ReactiveMP.jl
test/nodes/nodes_tests.jl

Fixes https://github.com/orgs/ReactiveBayes/discussions/376

Add a hint for the undefined factor nodes

---

Project.toml
test/runtests.jl

This PR should fix #434 .
Let me know if I need to add a test for this? It works now locally and Hwloc only triggers if CpuId fails (which is only in the case of ARM machines).
As soon as this works, I'll update the runtests.jl in the other packages accordingly.

fix #434: determine threads/cores via extra package Hwloc, if CpuId fails

---

docs/src/lib/nodes.md
src/nodes/nodes.jl
test/nodes/dependencies_tests.jl

This PR fixes #436 
This pull request include updates to the `ReactiveMP` library documentation and functionality, focusing on the customization of functional dependencies for nodes. The changes enhance the documentation, add new features for runtime customization, and includes tests to ensure the new functionality works as intended.
Users now can specify
```julia
function ReactiveMP.collect_functional_dependencies(::Type{CustomNode}, options::FactorNodeActivationOptions)
end
```
to set functional dependencies in runtime. `options` has an access to various settings, including metadata as requested in the original issue.

Enhance functional dependencies customization in ReactiveMP

---

src/rules/binomial_polya/y.jl
src/rules/predefined.jl
test/rules/binomial_polya/y_tests.jl

Add predictive distribution for BinomialPolya node
This PR implements the predictive distribution for the BinomialPolya node using Pólya-Gamma augmentation. The implementation includes:
- Message passing rule for predictive distribution 
- Support for both analytical and Monte Carlo approximations
Key features:
- Analytical approximation using mean of β when meta is nothing
- Monte Carlo sampling with configurable number of samples when meta is provided
- Returns Binomial distribution with averaged success probability
Files changed:
- src/rules/binomial_polya/y.jl: Added predictive distribution rule
- test/rules/binomial_polya/y_tests.jl: Tests

Add message for y interface of Binomial Polya

---

src/nodes/predefined/softdot.jl
test/nodes/predefined/softdot_tests.jl

In the current average energy computation for the softdot node under structured factorization assumption the indices in the following line `ar_slice(F, myx, (order + 1):(2order)), ar_slice(F, Vyx, (order + 1):(2order), (order + 1):(2order))` are inaccurate. Suppose x is 2d and \theta is also 2d. Then y is 1d. Meaning order is 2 in this case. In this example then the slice will range between 3:4 causing bounds error. This PR attempts to resolve this issue.

fix: softdot average energy

---

src/rules/discrete_transition/marginals.jl
test/rules/discrete_transition/marginals_tests.jl

Involves a nasty workaround if some of the incoming messages are `PointMass`. Nevertheless it should all work to fix FE computation in the `DiscreteTransition` node

Update marginal rules for `DiscreteTransition`

---

src/nodes/predefined/discrete_transition.jl
src/rules/discrete_transition/categoricals.jl
src/rules/discrete_transition/predefined/belief_propagation.jl
src/rules/discrete_transition/predefined/structured_vmp.jl

This pull request includes changes to the `DiscreteTransition` rules in several files, focusing on refining type constraints for `PointMass` and other related types. The most important changes include adding type constraints to improve type safety. This is useful if users implement `DiscreteTransition` with types that aren't necessarily `AbstractArrays` (like Tensor Decompositions) and which we can't naively multiply. This PR makes sure that the regular "rule not found error" will pop up rather than a multiplication error in the internals of the DiscreteTransition rules

Tighten the dispatch for the ruleset for DiscreteTransition

---

src/rules/addition/in1.jl
src/rules/addition/out.jl
test/rules/addition/out_tests.jl

`StaticArrays` broke in this place, and additionally you cannot call `gemv!` with mixed float type (for example `Float32` and `Float64`). New tests test this behaviour at least for `out` interface

Tighten dispatch for summation rules

---

src/approximations/linearization.jl
test/approximations/linearization_tests.jl

Fix #499 missing linearization method
