ReactiveBayes/ReactiveMP.jl

src/rules/normal_mixture/out.jl
src/rules/prototypes.jl

This PR adds output message for GaussianMixture node.

Add output message for GaussianMixture node

---

src/distributions/exp_linear_quadratic.jl
src/nodes/gamma_mixture.jl
src/nodes/gcv.jl
src/rules/gcv/k.jl
src/rules/gcv/w.jl
src/rules/gcv/z.jl

This pr adds kappa and omega update rules for the gcv node.

add rules for kappa and omega for gcv

---

src/distributions/exp_linear_quadratic.jl
src/nodes/gamma_mixture.jl
src/nodes/gcv.jl
src/rules/gcv/k.jl
src/rules/gcv/w.jl
src/rules/gcv/x.jl
src/rules/gcv/y.jl
src/rules/gcv/z.jl

This PR implements mean-field update rules and mean-field average energy function for the gcv node.

Develop gcv params

---

src/ReactiveMP.jl
src/distributions/mv_normal_mean_covariance.jl
src/distributions/mv_normal_mean_precision.jl
src/distributions/mv_normal_weighted_mean_precision.jl
src/distributions/normal_mean_precision.jl
src/distributions/normal_mean_variance.jl
src/distributions/normal_weighted_mean_precision.jl
src/nodes/subtraction.jl
src/rules/addition/marginals.jl
src/rules/prototypes.jl
src/rules/subtraction/in1.jl
src/rules/subtraction/in2.jl
src/rules/subtraction/marginals.jl
src/rules/subtraction/out.jl
test/distributions/test_mv_normal_mean_covariance.jl
test/distributions/test_mv_normal_mean_precision.jl
test/distributions/test_normal_mean_precision.jl
test/distributions/test_normal_mean_variance.jl
test/nodes/test_subtraction.jl
test/rules/addition/test_in1.jl
test/rules/addition/test_in2.jl
test/rules/addition/test_marginals.jl
test/rules/addition/test_out.jl
test/rules/subtraction/test_in1.jl
test/rules/subtraction/test_in2.jl
test/rules/subtraction/test_marginals.jl
test/rules/subtraction/test_out.jl
test/runtests.jl

I have created the subtraction rules and test scripts for creation and the out edge. Creation tests work but update rules for out edge are not recognized.

Extension rule subtraction

---

demo/Large-Scale Smoothing.ipynb
demo/Smoothing Benchmark.ipynb
src/nodes/mv_normal_mean_covariance.jl
src/nodes/mv_normal_mean_precision.jl
src/nodes/mv_normal_weighted_mean_precision.jl
src/nodes/normal_mean_precision.jl
src/nodes/normal_mean_variance.jl
src/rules/mv_normal_mean_covariance/marginals.jl
src/rules/mv_normal_mean_precision/marginals.jl
src/rules/normal_mean_precision/marginals.jl
src/rules/normal_mean_precision/mean.jl
src/rules/normal_mean_precision/out.jl
src/rules/normal_mean_variance/marginals.jl
src/rules/normal_mean_variance/mean.jl
src/rules/normal_mean_variance/out.jl
test/rules/normal_mean_precision/test_mean.jl
test/rules/normal_mean_precision/test_out.jl
test/rules/normal_mean_variance/test_mean.jl
test/rules/normal_mean_variance/test_out.jl

This PR fixes `GaussianMeanPrecision` node rules to handle all Gaussian parametrisation cases.
Thanks to @ismailsenoz

feat(): extra Gaussian nodes family rules and performance improvements

---

src/nodes/gcv.jl
src/rules/gcv/k.jl
src/rules/gcv/w.jl
src/rules/gcv/z.jl

This PR makes the GCV node a bit more efficient.

fix(): Fix performance regression in HGF

---

src/score.jl

Previously `score()` function did not take into account `degree()` of `PointMass` estimates. This PR fixes it. 
Now FE computation completely ignores variables with `PointMass` form constraint and simply cancel out all possible infinities at the end of the procedure.

fix(): Fix FE computations for EM

---

src/nodes/uninformative.jl

make uninformative node stochastic

---

src/rules/normal_mean_variance/var.jl
test/rules/normal_mean_variance/test_var.jl

Fixes #96. @albertpod, @bartvanerp, @ismailsenoz please double check.

Fix :var messages

---

src/variables/data.jl

This PR possibly fixes mysterious Julia's segmentation fault encountered by @abpolym during async inference execution.

fix: simplify update! function

---

src/variables/data.jl
src/variables/random.jl
test/variables/test_data.jl
test/variables/test_random.jl

feat: error message when directly indexing variables in a model

---

src/distributions/wishart.jl
src/nodes/wishart.jl

Fix average energy for Wishart

---

src/inference.jl

feat: allow more options for returnvars

---

docs/src/lib/prod.md
src/constraints/prod/prod_generic.jl
src/distributions/function.jl
test/constraints/prod/test_prod_generic.jl
test/runtests.jl

feat: linearise non-analytical product for objects of the same type

---

src/distributions/wishart.jl
src/nodes/wishart.jl

refactoring: replace `dim` with `size`

---

demo/Eight school cvi.ipynb
src/nodes/delta/approximations/cvi.jl
src/nodes/delta/delta.jl
src/rules/delta/marginals.jl
src/rules/delta/out.jl

This PR adds custom rule layout feature in DeltaFn node for CVI approximation

Add custom rule layout for CVI approximation

---

src/distributions/contingency.jl
src/distributions/dirichlet.jl
src/distributions/pointmass.jl
src/helpers.jl
src/nodes/categorical.jl
src/nodes/transition.jl
test/distributions/test_contingency.jl
test/test_helpers.jl

fix: add clamplog

---

src/distributions/normal.jl
test/distributions/test_normal.jl

This PR adds extra rand methods and adds extra tests for mv gaussians implementations

add extra rand methods for mv gaussians

---

src/constraints/spec/factorisation_spec.jl
src/constraints/spec/spec.jl
src/marginal.jl
src/message.jl
src/nodes/gamma_mixture.jl
src/nodes/normal_mixture.jl
test/constraints/spec/test_factorisation_spec.jl
test/models/test_gmm.jl

fix constraints specification resolution for tupled variables

---

src/inference.jl

Fix showprogress = true when iterations are not specified

---

src/algebra/correction.jl
src/nodes/gcv.jl
src/rule.jl
src/rules/and/in2.jl
src/rules/gcv/marginals.jl
src/rules/gcv/x.jl
src/rules/gcv/y.jl
src/rules/multiplication/A.jl
src/rules/multiplication/in.jl
src/rules/multiplication/marginals.jl
src/rules/multiplication/out.jl
src/rules/probit/in.jl
src/rules/probit/out.jl
src/score.jl
test/models/test_hgf.jl
test/test_rule.jl

Change default meta spec from `Any` to `Nothing`

---

src/rules/normal_mixture/out.jl
test/rules/normal_mixture/test_out.jl

Updated Gaussian Mixture update and refined tests

Updated Gaussian Mixture update rules

---

src/distributions/wishart.jl
src/nodes/mv_normal_mean_precision.jl
src/nodes/normal_mixture.jl
src/rules/normal_mixture/m.jl
src/rules/normal_mixture/p.jl
src/rules/normal_mixture/switch.jl
test/nodes/test_normal_mixture.jl
test/rules/normal_mixture/test_m.jl
test/rules/normal_mixture/test_p.jl
test/rules/normal_mixture/test_switch.jl
test/runtests.jl

Gaussian Mixture node rules are updated to leverage dispatch options and test cases are added.

224 gaussian mixture relax constraints all around

---

src/distributions.jl
src/distributions/normal.jl
src/helpers/macrohelpers.jl
src/rule.jl
test/distributions/test_normal.jl
test/rules/delta/linearization/test_in.jl
test/rules/delta/linearization/test_marginals.jl
test/rules/delta/linearization/test_out.jl
test/test_distributions.jl

We now can differentiate the code that differentiates!

test: add more tests for the Linearization approximation

---

src/ReactiveMP.jl
src/nodes/mixture.jl
src/rules/mixture/inputs.jl
src/rules/mixture/out.jl
src/rules/mixture/switch.jl
src/rules/prototypes.jl

Addresses #262.
Perhaps let's wait with the merge, because of recently submitted demo. Unless `Pluto` also tracks package versions ofc.

Rename `Switch` to `Mixture`

---

src/approximations/cvi.jl

This PR clarifies the CVI implementation and sets `warn = true` by default.

feat(cvi): improve docs and warn by default

---

src/distributions/beta.jl
test/approximations/test_cvi.jl
test/distributions/test_beta.jl

The purpose of this pull request is to make the functionality of the CVI **to run** with the Beta distribution. The following changes have been made: `BetaNaturalParameters` is implemented (with tests): the logpdf, the lognormalizer, constructors.
Also, a basic CVI **run** test is added: it checks only that CVI is running with Beta, the actual prod quality is not checked.

Beta distribution natural parameters

---

test/approximations/test_cvi.jl

The following changes have been made in this pull request:
1. The convergence failed warning inside empty optimiser tests has been suppressed to avoid confusion.
2. The convergence warning has been included in all tests where we compare the CVI result with the analytical solution.
3. The tolerance level is smaller: we expect solutions to be more precise than it was before.
This PR resolves https://github.com/biaslab/ReactiveMP.jl/issues/280.

Make CVI tests less confusing

---

src/score/score.jl

fix: change default meta type in average energy from Any to Nothing

---

src/nodes/autoregressive.jl
test/nodes/test_autoregressive.jl
test/rules/autoregressive/test_gamma.jl
test/rules/autoregressive/test_marginals.jl
test/rules/autoregressive/test_theta.jl
test/rules/autoregressive/test_x.jl
test/rules/autoregressive/test_y.jl
test/runtests.jl

This pull request includes a comprehensive test set for AR, although it is not fully complete (~80% finished).

Add tests for AR node

---

src/addons/memory.jl
test/addons/test_memory.jl
test/test_addons.jl

fix erroneous Base.show method for MemoryAddon

---

src/distributions/gamma.jl
src/distributions/gamma_shape_rate.jl
test/distributions/test_gamma.jl

This PR resolves issue https://github.com/biaslab/ReactiveMP.jl/issues/314.

Fix GammaShapeRate pdf

---

.github/workflows/ci.yml

This PR adds Julia 1.9 to the tests

use Julia 1.9 in tests

---

src/approximations/linearization.jl
test/rules/delta/linearization/test_out.jl

This PR addresses #328 by adding a missing method for the scenario.

Fix Linearization method for multivariate input univariate output

---

src/rule.jl
src/score/score.jl
test/rules/multiplication/test_in.jl
test/test_rule.jl

add check for input arguments in the rules

---

src/distributions/sample_list.jl
test/distributions/test_sample_list.jl

Define the mean function for a sample list with respect to an arbitrary function

---

README.md

This PR fixes the Zenodo URL, they had an update recently

Update Zenodo URL/label in README.md

---

.github/workflows/ci.yml
test/rules/continuous_transition/test_marginals.jl

This PR changes CI to use Julia 1.10 for tests

Use Julia 1.10 for tests

---

test/nodes/test_continuous_transition.jl
test/rules/continuous_transition/test_W.jl
test/rules/continuous_transition/test_a.jl
test/rules/continuous_transition/test_x.jl
test/rules/continuous_transition/test_y.jl

Remove warnings

---

.github/workflows/ci.yml

Use julia-actions/cache for CI

---

src/nodes/softdot.jl

This PR fixes the FE of softdot: change all marginals to Any

fix FE softdot: marginals to Any

---

Project.toml
src/variables/random.jl
test/nodes/predefined/delta/delta_tests.jl
test/variables/random_tests.jl

This PR fixes wrong initialisation for https://github.com/biaslab/MultiAgentTrajectoryPlanning/issues/4
Linked together with PR in RxInfer where the actual model is being tested, but this PR must be merged and tagged first.

Fix for MultiAgentTrajectoryPlanning#4

---

src/approximations/linearization.jl

Cleanup Linearization code

---

src/approximations/unscented.jl

This is a temporary fix for recent failures in RxInfer

Make the computation of v tilde within Unscented more stable

---

src/helpers/algebra/companion_matrix.jl
src/helpers/algebra/permutation_matrix.jl
src/helpers/algebra/standard_basis_vector.jl
src/helpers/helpers.jl
src/marginal.jl
src/message.jl
src/nodes/predefined/autoregressive.jl
src/nodes/predefined/gcv.jl
src/pipeline/logger.jl
src/rule.jl
test/rule_tests.jl

This PR removes some of the methods that aren't required, but create extra burden on Julia compiler and causes compilation invalidation and extra latencies

Fix invalidations from SnoopCompile

---

src/pipeline/logger.jl

Not sure why its happening, but this fixes it

Fix infinite printing in RxInfer documentation

---

src/rule.jl
test/rule_tests.jl

Fixes issues from https://github.com/orgs/ReactiveBayes/discussions/491 by @ofSingularMind

update rule error printing, adds meta spec
